package reports;

import android.graphics.Color;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import com.example.android.swn.R;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;

import lecho.lib.hellocharts.model.Axis;
import lecho.lib.hellocharts.model.AxisValue;
import lecho.lib.hellocharts.model.Line;
import lecho.lib.hellocharts.model.LineChartData;
import lecho.lib.hellocharts.model.PointValue;
import lecho.lib.hellocharts.model.SimpleValueFormatter;
import lecho.lib.hellocharts.view.LineChartView;


/**
 * Created by kumudini on 9/23/14.
 */
public class TimeBasedReportFragment extends Fragment {

    private View rootView;
    private List<Integer> xAxisValues = new LinkedList<Integer>();
    private List<Float> yAxisValues = new LinkedList<Float>();
    private static final String LOG_TAG = TimeBasedReportFragment.class.getSimpleName();

    public TimeBasedReportFragment() {
    }
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        rootView = inflater.inflate(R.layout.fragment_time_based_chart, container, false);

        xAxisValues = (List<Integer>) getArguments().getSerializable("xAxisValues");
        List<AxisValue> days = new LinkedList<AxisValue>();
        for (int value : xAxisValues)
            days.add(new AxisValue(value));

        yAxisValues = (List<Float>) getArguments().getSerializable("yAxisValues");
        List<AxisValue> consumption = new LinkedList<AxisValue>();
        for (float value : yAxisValues)
            consumption.add(new AxisValue(value));

        List<PointValue> values = new ArrayList<PointValue>();
        for (int i = 0; i < days.size(); i++) {
            values.add(new PointValue(days.get(i).getValue(), consumption.get(i).getValue()));
        }

        Line line = new Line(values).setColor(Color.BLUE).setCubic(true);
        List<Line> lines = new ArrayList<Line>();
        lines.add(line);

        LineChartData data = new LineChartData();
        data.setLines(lines);
        Axis xAxis = new Axis();
        xAxis.setName("Time(Sep 1 to Sep 5)");
        xAxis.setAutoGenerated(false);
        xAxis.setValues(days);
        xAxis.setTextColor(Color.BLACK);

        xAxis.setValues(days);
        xAxis.setFormatter(new SimpleValueFormatter(0,false, null, null));
        data.setAxisXBottom(xAxis);
        Axis yAxis = new Axis();
        yAxis.setHasLines(true);
        yAxis.setName("Water Consumption(in Lakh liters)");
        yAxis.setTextColor(Color.BLACK);
        data.setAxisYLeft(yAxis);

        LineChartView lineChartView = (LineChartView) rootView.findViewById(R.id.linechart);
        lineChartView.setLineChartData(data);
        lineChartView.setZoomEnabled(true);
        lineChartView.setScrollEnabled(false);

        return rootView;
    }
}
